### ISSUE TITLE
Rework Video Streaming

### ISSUE THREAD

**Issue by ShujianDou** [vrienstudios/anime-dl#110]
Currently, video streams stream a series of bytes to VLC; however, I wish to rework this, which would allow the ability to seek within the streamed files.

This may entail a complete reworking of the current M3U.cs file to work concurrently and adapt to requests for seeking HLS and MP4 streams based on approximate video length.

**Comment by ShujianDou** [comment]
HLS -> Create a communication server, which will communicate with VLC. VLC will be fed a constructed manifest, which would allow for seeking while continuously downloading to disk. This will most likely be the last step, before I go to implement video into the android and desktop applications.

**Comment by GABIlopez** [comment]
App anime

**Comment by GABIlopez** [comment]
Android

**Comment by ShujianDou** [comment]
I plan on an Android version, but I'm just too busy, currently, to do active development of any new apps or UI features.

**Comment by ShujianDou** [comment]
@GABIlopez In the meantime, you can try this site: http://simple-anime.herokuapp.com/home

It is ad-free, and it should work alright on mobile (though, no downloads)

**Comment by ShujianDou** [comment]
Closed, as video streaming has been fully converted to HLSManager (with the exception of Twist.moe, which returns a .mp4)
