### ISSUE TITLE
    Error:  Package ADLCore@0.2.0 not found.

### ISSUE THREAD

**Issue by zand951** [vrienstudios/anime-dl#147]
When install using nimble

**Comment by ShujianDou** [comment]
Did you do `nimble installdeps` first?

Here's a list of requirements, if you'd wish to install them manually:

https://github.com/ShujianDou/nim-HLSManager
https://github.com/ShujianDou/nim-epub
https://github.com/ShujianDou/halonium.git
https://github.com/vrienstudios/ADLCore.git
https://github.com/vrienstudios/zippy

nimcrypto
nimscripter

You can find them in the .nimble files of vrienstudios/ADLCore and anime-dl.
