### ISSUE TITLE
API

### ISSUE THREAD

**Issue by sb-gravity100** [vrienstudios/anime-dl#27]
I noticed it's only used on the command line... that's all

**Comment by ShujianDou** [comment]
Noticed that the API project is only used on the command line?

**Comment by ShujianDou** [comment]
The API is also used in the mobile app, but it is not tested; I also do not know if it works. There is not any GUI/UI for this project yet, and there probably will not be one in the near future. If you need anything or have a question, feel free to comment, message me, or open up a new issue.
