### ISSUE TITLE
support for vidcloud9 (similar to vidstreaming)

### ISSUE THREAD

**Issue by ayunami2000** [vrienstudios/anime-dl#67]
although not anime, it works extremely similar.

also heres a list of every domain u will need including vidcloud9 ones:

- vidcloud9.com
- streamani.net
- animeid.to
- asianload.cc
- k-vid.co
- asianload.io
- vidnext.net
- gogo-play.net
- vidnode.net
- gogo-stream.com
- gogo-play.tv
- vidembed.net
- vidstreaming.io

**Comment by ShujianDou** [comment]
Since all of these are all extremely similar, I doubt I will have to even rewrite anything. Thanks for the domains, and sorry for getting to the issue pretty late.

**Comment by ShujianDou** [comment]
Finished
